services:
  postgres:
    image: postgres:16-alpine
    container_name: milos_milbyte-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: milos_milbyte
    ports:
      - '5437:5437'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d milos_milbyte']
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: milos_milbyte-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5437/milos_milbyte?schema=public
    ports:
      - '3000:3000'

volumes:
  postgres_data:
